# Generated by Django 2.0.1 on 2019-03-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('hangye', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('buildTime', models.CharField(max_length=32)),
                ('tags', models.CharField(max_length=128)),
                ('weixinhao', models.CharField(max_length=32)),
                ('imgUrl', models.CharField(max_length=128)),
                ('imgPath', models.CharField(max_length=128)),
            ],
        ),
    ]
