# Generated by Django 2.0.1 on 2019-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxqInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quninfo',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
